#!/bin/sh
set -euf

##
# Generate a random line that looks like a SSH keygen fingerprint.
#
# Usage:
#
#     random-ssh-fingerprint
#
# Example:
#
#     $ random-ssh-fingerprint
#     256 SHA256:TotrDXxFMixUbaXOjx+JOiXQcwayIzKRZwRcXHRXbPAb 179.241.130.243 (ECDSA)
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

echo "256 SHA256:$(random-sha-256-checksum) $(random-ip-address) (ECDSA)"
