#!/bin/sh
set -euf -o pipefail

##
# Generate a random password for high security needs.
#
# Usage:
#
#     random-password [n]
#
# Options:
#
#     * n is an optional length; it defaults to 16.
#
# Example:
#
#     $ random-password
#     cbfbcdegpiceklpa
#
# This uses /dev/urandom to generate random characters.
# This is high security and suitable for cryptography.
#
# This script then filters the characters to pick just the
# ones that match the first 16 letters: abcdefghijklmnop.
# 
# We choose to use exactly 16 characters because these have
# useful mathematical properties for generating security
# values, and also for calculating password strength.
#
# Some password-checker tools may report these passwords
# are insecure because they only have lowercase letters.
# This is true *if* you are overriding the defaults by
# using 8 letters or less; hackers have pre-computed all
# short lowercase passwords using "rainbow table" lookups.
#
# Mathematically, using 16 different characters  letters
# are more computationally secure than 9 mixed characters.
# If you prefer to use more security, use more letters.
#
# Command: random-password
# Version: 4.0.0
# Created: 2010-05-20
# Updated: 2017-01-13
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

len=${1-16}
LC_ALL=C < /dev/urandom tr -dc "abcdefghijklmnop" | head -c"$len"
