#!/bin/sh
set -euf

##
# Seed the bash random number generator using /dev/urandom
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

RANDOM=$(head -c4 /dev/urandom | od -t u4 | awk '{ print $2 }')
