#!/bin/sh
set -euf

##
# Generate a random LinkedIn app API key,
#
# The string is alphanumeric lowercase 12 characters.
#
# Usage:
#
#     random-linkedin-app-api-key [n]
#
# Example:
#
#     $ random-linkedin-app-api-key
#     voqktpwdsopxq
#
# See http://linkedin.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:lower:][:digit:]' "${1:-12}"
