#!/bin/sh
set -euf

##
# Generate a random Facebook app id string.
#
# The string is digits, 15 characters.
#
# Usage:
#
#     random-facebook-app-id [n]
#
# Example:
#
#     $ random-facebook-app-id
#     567337611380931
#
# See http://facebook.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:digits:]' "${1:-15}"
