#!/bin/sh
set -euf

##
# Generate a random git commit hash.
#
# Usage:
#
#     random-git-commit-hash [n]
#
# Example:
#
#     $ random-git-commit-hash
#     37004A3B3427BE452DDB8E681EAB58A6
#
# This implemenation uses the commands `hexdump` and `/dev/urandom`.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-hex-upper "${1:-20}"
