#!/bin/sh
set -euf

##
# Generate a random Amazon Web Services (AWS) Simple Email Service (SES)
# Simple Mail Transfer Protocol (SMTP) username string.
#
# The string is alphabetic, uppercase, 20 characters.
#
# Usage:
#
#    random-aws-ses-smtp-username
#
# Example:
#
#    $ random-aws-ses-smtp-username
#    SYEKEHQILMOKVIMZGRXJ
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:upper:]' "${1-20}"
