#!/bin/sh
set -euf

##
# Generate a random Apple development id string.
#
# The string is alphanumeric, uppercase, 10 characters.
#
# Usage:
#
#     random-apple-development-id [n]
#
# Options:
#
#   * `n` is the number of characters; default is 10.
#
# Example:
#
#     $ random-apple-development-id
#     YT4K6BX2UZ
#
# See http://developer.apple.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:upper:][:digit:]' "${1:-10}"
