#!/bin/sh
set -euf

##
# Generate a Amazon Web Services (AWS) Simple Email Service (SES)
# Simple Mail Transfer Protocol (SMTP) password string.
#
# The string is alphanumeric and symbols "+" "/" and 43 characters.
#
# Usage:
#
#     random-aws-ses-smtp-password [n]
#
# Options:
#
#   * `n` is the number of characters; default is 43.
#
# Example:
#
#     $ random-aws-ses-smtp-password
#     uj5\Tk47oqJ+YBSXxTaeZXnN/2N3rMfTwVU+np+f20
#
# Version: 2.0.0
# Updated: 2020-03-23
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

random-ascii '[:alnum:]\+\/' ${1-43}
