#!/bin/bash
set -euf -o pipefail

##
# Generate a random uuid string.
#
# Usage:
#
#     random-uuid
#
# Example:
#
#     $ random-uuid
#     902dba9d-d7ba-f8f6-7038-472d75d232e7
#
# The UUID format is defined in RFC 4122, ISO/IEC 9834-8:2005,
# and related standards.
#
# This script uses the commands `hexdump` and `/dev/random`
# to generate secure random numbers and format them.
#
# A UUID may be represented either in uppercase or lowercase.
# Lowercase is common in Unix; uppercase is common on Windows.
#
# If your system has the `uuidgen` tool, consider using it
# instead because it's faster; use the `-r` random flag.
#
# Example uuidgen on Linux:
#
#     $ uuidgen -r
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

hexdump -n 16 -v -e '4/1 "%02X" "-" 2/1 "%02X" "-" 2/1 "%02X" "-" 2/1 "%02X" "-" 6/1 "%02X" "\n"' /dev/random | tr 'a-f' 'A-F'
