#!/bin/sh
set -euf

##
# Generate a secure random die roll 1-6
#
# Usage:
#
#     random-die-6 [n]
#
# Options:
#
#   * `n` is the number of characters; default is 1.
#
# Example:
#
#     random-die-6
#     #=> 6
#
#     random-die-6 3
#     #=> 614
#
# This implementation uses `/dev/urandom`
# and `tr` to select matching characters.
#
# Depending on your own systems and security needs,
# you may want to adjust this script by changing the
# system command `/dev/urandom` to `/dev/urandom`.
# This change will make the script non-blocking.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

len=${1-1}
LC_ALL=C < /dev/urandom tr -dc "123456" | head -c"$len"
