#!/bin/sh
set -euf

##
# Generate a random TestFlight API token string.
#
# The string is 32 character hexadecimal lowercase string,
# then a dash, then a 44 character alphanum string.
#
# See http://testflightapp.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

part1=$(random-hex-lower 16)
part2=$(random-ascii '[:alnum:]' 44)
echo "${part1}_${part2}"
