#!/bin/sh
set -euf

##
# Generate a random Amazon Web Services (AWS) PEM key pair fingerprint.
#
# Usage:
#
#     random-aws-pem-fingerprint [n]
#
# Options:
#
#   * `n` is the number of bytes; default is 20.
#
# Example:
#
#     $ random-aws-pem-fingerprint
#     af:6f:ff:6f:0f:ff:f9:6f:31:40:f9:4f:f4:96:71:ff:0f:25:76:f5
#
# This implementation uses `hexdump` and `/dev/urandom`.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-hex-lower-fingerprint "${1:-20}"
