#!/bin/sh
set -euf

##
# Generate a Amazon Web Services (AWS) Simple Email Service (SES)
# Simple Mail Transfer Protocol (SMTP) password string.
#
# The string is alphanumeric and symbols "+" "/" and 43 characters.
#
# Usage:
#
#     random-aws-ses-smtp-password [n]
#
# Options:
#
#   * `n` is the number of characters; default is 43.
#
# Example:
#
#     $ random-aws-ses-smtp-password
#     uj5\Tk47oqJ+YBSXxTaeZXnN/2N3rMfTwVU+np+f20
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:alnum:]\+\/' "${1-43}"
