#!/bin/bash
set -euf -o pipefail

##
# Generate a random Microsoft Azure subscription id string.
#
# Usage:
#
#     random-azure-subscription-id
#
# Example:
#
#     $ random-azure-subscription-id
#     902dba9d-d7ba-f8f6-7038-472d75d232e7
#
# This script uses the commands `hexdump` and `/dev/urandom`
# to generate secure random numbers and format them.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2016-11-01
##

hexdump -n 16 -v -e '4/1 "%02x" "-" 2/1 "%02x" "-" 2/1 "%02x" "-" 2/1 "%02x" "-" 6/1 "%02x" "\n"' /dev/urandom
