#!/bin/sh
printf "User name,Password,Access key ID,Secret access key,Console login link"
printf "$(random-email-addr),$(random-password),$(random-aws-access-key-id),$(random-aws-secret-access-key),https://example.signin.aws.amazon.com/console"
