#!/bin/sh
set -euf

##
# Generate a random Etsy API key.
#
# The string is alphanumeric, lowercase, 24 characters.
#
# Usage:
#
#     random-etsy-api-key [n]
#
# Example:
#
#     $ random-etsy-api-key
#     627af3ciipjhja1irz28j4mu
#
# See https://www.etsy.com/developers/
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:lower:][:dight:]' "${1:-24}"
