#!/bin/sh
set -euf

##
# Generate a random Mixpanel.com token.
#
# This is a 32 character hexadecimal lowercase string.
#
# Usage:
#
#     random-mixpanel-token
#
# Example:
#
#     $ random-mixpanel-token
#     314aded16e28a4f9d16755ba9c6730bc
#
# See http://mixpanel.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-hex-lower ${1-16}
