#!/bin/sh
set -euf

##
# Generate a random TestFlight app_token string.
#
# The string is a uuid, lowercase.
#
# Usage:
#
#     random-testflight-app-token
#
# Example:
#
#     $ random-testflight-app-token
#     a49b80e8-8836-46a2-a7c6-5ab8f0ac9ddc
#
# For details, see http://testflightapp.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-uuid-lower
