#!/bin/sh
set -euf

##
# Generate a random file that fills up forever with random data.
#
# This can be useful to wipe a disk drive, or for load testing, etc.
#
# The file name is a random 32-hex-character-lowercase string.
#
# Usage:
#
#     random-file-infinite
#
# Examples:
#
#     $ random-file-infinite
#     #=> write random data to file "76ba7ad7d9265466f2ad764c4d5859f5"
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

cat /dev/urandom > $(hexdump -n 16 -v -e '16/1 "%02x"' /dev/urandom)
