#!/bin/sh
set -euf

##
# Generate a random string that looks like a SHA 256 checksum.
#
# Usage:
#
#     random-sha-256 [n]
#
# Options:
#
#   * `n` is the number of characters; default is 44.
#
# Example:
#
#     $ random-sha-256
#     IBYMhAiRHPDJAamWSafFk+XirjkiTFqEGSFTOnWWTAVS
#
# Version: 2.0.0
# Updated: 2020-03-24
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

random-ascii '[:alpha:]\+' ${1-44}
