#!/bin/sh
set -euf

##
# Generate a random Etsy shop id string.
#
# The string is alphabetic, mixed case, 4-64 characters.
#
# Syntax:
#
#     random-etsy-shop-id [n]
#
# Options:
#
#   * `n` is the number of characters; default is 4-64.
#
# Example:
#
#     $ random-etsy-shop-id
#     oRcIJbwcwXHUVOyHPFeHTKicenPsxttC
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

n=${1-$(( $RANDOM % 60 + 4 ))}
random-ascii '[:alpha:]' $n
