#!/bin/sh
set -euf

##
# Generate a random git commit hash.
#
# Usage:
#
#     random-git-commit-hash
#
# Example:
#
#     $ random-git-commit-hash
#     37004A3B3427BE452DDB8E681EAB58A6
#
# This implemenation uses the commands `hexdump` and `/dev/urandom`.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

hexdump -n 20 -v -e '/1 "%02X"' -e "/20 \"\n\"" /dev/urandom | tr '[:upper:]' '[:lower:]'
