#!/bin/sh
set -euf

##
# Generate a random Trello short link.
#
# The string is alphanumeric, mixed case, 8 characters.
#
# Usage:
#
#     random-trello-short-link [n]
#
# Example:
#
#     $ random-trello-short-link
#     6x7af3cq3
#
# See https://www.trello.com/api/
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:alnum:]' "${1:-8}"
