#!/bin/bash
set -euf -o pipefail

##
# Generate a random Datawire.io token string.
#
# The string is alphanumeric 539 characters.
#
# Usage:
#
#     random-datawire-token
#
# Example:
#
#     $ random-datawire-token
#     rh082vn0gapaqjitzszlnc46...
#
# See https://datawire.io
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2017-02-20
##

random-alphanum 539
