#!/bin/sh
set -euf

##
# Generate a random Segment.io Analytics secret key string.
#
# The string is alphanumeric, lowercase, 10 characters.
#
# Usage:
#
#     random-segment-analytics-secret
#
# Example:
#
#     $ random-segment-analytics-secret
#     ilao5b9x5d
#
# See http://segment.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:lower:][:dight:]' ${1-10}
