#!/bin/sh
set -euf

##
# Generate a random TestFlight team token string.
#
# The string is a 32 character hexadecimal lowercase string,
# then an underscore, then a 44 character alphanum string.
#
# Usage:
#
#     random-testflight-team-token
#
# Example:
#
#     $ random-testflight-team-token
#     314aded16e28a4f9d16755ba9c6730bc_9UKTvH9JV5m5RlYjW0jdUs1ODwFWQkQ5du5Qapxc9J5X
#
# See http://testflightapp.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

part1=$(random-hex-lower 16)
part2=$(random-ascii '[:alnum:]' 44)
echo "${part1}_${part2}"
