#!/bin/sh
set -euf

##
# Generate a Amazon Web Services (AWS) Secret Access Key.
#
# The string is alphanumeric mixed case and symbols "+", "/", and 40 characters.
#
# Usage:
#
#     random-aws-secret-access-key [n]
#
# Options:
#
#   * `n` is the number of characters; default is 40.
#
# Example:
#
#     $ random-aws-secret-access-key
#     ikb+mgBUoPytLBMdY64YLdW+EZLNJ13Kty+mc071
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:alnum:]\+\/' "${1:-40}"
