#!/bin/sh
set -euf

##
# Generate a random Twitter app consumer key.
#
# The string is alphanumeric, mixed case, 21 characters.
#
# Usage:
#
#     random-twitter-app-consumer-key [n]
#
# Options:
#
#   * `n` is the number of characters; default is 21.
#
# Example:
#
#     $ random-twitter-app-consumer-key
#     NIqmCufaqpSvKyYXMRMaF
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:alnum:]' ${1-21}
