#!/bin/sh
set -euf

##
# Generate a Amazon Web Services (AWS) Secret Access Key.
#
# The string is alphanumeric mixed case and symbols "+", "/", and 40 characters.
#
# Usage:
#
#     random-aws-secret-access-key [n]
#
# Options:
#
#   * `n` is the number of characters; default is 40.
#
# Example:
#
#     $ random-aws-secret-access-key
#     ikb+mgBUoPytLBMdY64YLdW+EZLNJ13Kty+mc071
#
# Version: 2.0.0
# Updated: 2020-03-24
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

random-ascii '[:alnum:]\+\/' "${1:-40}"
