#!/bin/sh
set -euf

##
# Generate a random passphrase for high security needs.
#
# Usage:
#
#     random-passphrase [n]
#
# Options:
#
#     * n is an optional length; it defaults to 64.
#
# Example:
#
#     $ random-passphrase
#     svwcsnvyvuapdmuxqatwdepvtjgvtwzadwfzvnwpsbdcbeufsedhyeywwxzxpymy
#
# Command: random-passphrase
# Version: 4.0.0
# Created: 2010-05-20
# Updated: 2021-10-14T17:58:40Z
# License: BSD or MIT or GPL or contact us for custom license
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

len=${1-64}
random-password $len
