#!/bin/sh
set -euf

##
# Generate a random Crittercism.com App Id string.
#
# The string is alphanumeric, lowercase, 24 characters.
#
# Usage:
#
#     random-crittercism-app-id [n]
#
# Example:
#
#     $ random-crittercism-app-id
#     rh082vn0gapaqjitzszlnc46
#
# See http://crittercism.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:lower:][:dight:]' "${1:-24}"
