#!/bin/sh
set -euf

##
# Generate a random string that looks like a PGP key identifier.
#
# Usage:
#
#     random-pgp-key-id [n]
#
# Options:
#
#   * `n` is the number of characters; default is 40.
#
# Example:
#
#     $ random-pgp-key-id
#     8191730CDC3EE29DA7CDE474B932B8AFC3D20BFB
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-hex-upper ${1-40}

