#!/bin/sh
set -euf

##
# Generate a random Apple development id string.
#
# The string is alphanumeric, uppercase, 10 characters.
#
# Usage:
#
#     random-apple-development-id [n]
#
# Options:
#
#   * `n` is the number of characters; default is 10.
#
# Example:
#
#     $ random-apple-development-id
#     YT4K6BX2UZ
#
# See http://developer.apple.com
#
# Version: 2.0.0
# Updated: 2020-03-24
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

random-ascii '[:upper:][:digit:]' "${1:-10}"
