#!/bin/sh
echo "User name,Password,Access key ID,Secret access key,Console login link"
echo "alice@example.com,$(random-password),$(random-aws-access-key-id),$(random-aws-secret-access-key),https://example.signin.aws.amazon.com/console"

