#!/bin/sh
set -euf

##
# Generate a random Microsoft Azure subscription id string.
#
# Usage:
#
#     random-azure-subscription-id
#
# Example:
#
#     $ random-azure-subscription-id
#     902dba9d-d7ba-f8f6-7038-472d75d232e7
#
# This script uses the commands `hexdump` and `/dev/urandom`
# to generate secure random numbers and format them.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-uuid-lower
