#!/bin/sh
set -euf

##
# Generate a random Twitter app consumer secret.
#
# The string is alphanumeric, mixed case, 42 characters.
#
# Usage:
#
#     random-twitter-app-consumer-secret [n]
#
# Options:
#
#   * `n` is the number of characters; default is 42.
#
# Example:
#
#     $ random-twitter-app-consumer-secret
#     ksk6Xu4echm9qSCJsRdLOeK1TiJiceTWeJrY26U9V1
#
# See http://twitter.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:alnum:]' ${1-42}
