#!/bin/sh
set -euf

##
# Generate a random hex MAC address.
#
# Usage:
#
#     random-mac-address [n]
#
# Options:
#
#   * `n` this the number of bytes; default is 6.
#
# Example:
#
#     $ random-mac-address
#     58:bc:f8:52:2b:c2
#
# This implementation uses `hexdump` and `/dev/urandom`.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-hex-lower-fingerprint ${1-6}
