#!/bin/sh

##
# Generate a random time second, in the range 0-59.
#
# Usage:
#
#     random-second
#
# Examples:
#
#     $ random-second
#     #=> 59
#
# This script does NOT seed the shell random variable.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

echo $(( RANDOM % 60))
