#!/bin/sh
set -euf

##
# Generate a random string of word characters.
#
# The characters are A-Z, a-z, and underscore.
#
# Usage:
#
#     random-word-characters [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Examples:
#
#     $ random-word-characters
#     UT_QPCfk_zhQNhpB
#
#     $ random-word-characters 8
#     YpGm_pmE
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:alnum:]_' ${1-16}
