#!/bin/sh
set -euf

##
# Generate a random string that looks like an IP address.
#
# Usage:
#
#     random-ip-address
#
# Example:
#
#     $ random-ip-address
#     128.129.130.131
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

a=$(( 130 + $(( $RANDOM % 120 ))))
b=$(( 130 + $(( $RANDOM % 120 ))))
c=$(( 130 + $(( $RANDOM % 120 ))))
d=$(( 130 + $(( $RANDOM % 120 ))))
echo "$a.$b.$c.$d"
