#!/bin/bash
set -euf -o pipefail

##
# Generate a secure random numeric id
#
# Usage:
#
#     random-nid
#
# Example:
#
#     random-nid
#     #=> 8125681425681428762
#
# The term "nid" is our shorthand for secure
# random numeric id that uses digits 1-8,
# exactly 19 times.
#
# This has desireable properties:
#
#   * All numbers are the same length
#   * No leading zero
#   * Fits in an 8-byte integer representation
#   * Translatable to octal if need.
# 
# This implementation uses `/dev/urandom`
# and `tr` to select matching characters.
#
# Depending on your own systems and security needs,
# you may want to adjust this script by changing the
# system command `/dev/urandom` to `/dev/urandom`.
# This change will make the script non-blocking.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

len=19
LC_ALL=C < /dev/urandom tr -dc "12345678" | head -c"$len"
