#!/bin/sh
set -euf

##
# Generate a Amazon Web Services (AWS) Access Key Id.
#
# The string is alphanumeric uppercase and 20 characters.
#
# Usage:
#
#     random-aws-access-key-id [n]
#
# Options:
#
#   * `n` is the number of characters; default is 20.
#
# Example:
#
#     $ random-aws-access-key-id
#     XQX20V9LO8ARDI10QFVG
#
# Version: 2.0.0
# Updated: 2020-03-24
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

random-ascii '[:upper:][:digit:]' "${1:-20}"
