#!/bin/sh
set -euf -o pipefail

##
# Generate a Amazon Web Services (AWS) Secret Access Key.
#
# The string is alphanumeric mixed case and the "+" symbol, and 40 characters.
#
# Usage:
#
#     random-aws-secret-access-key
#
# Example:
#
#     $ random-aws-secret-access-key
#     ikb+mgBUoPytLBMdY64YLdW+EZLNJ13Kty+mc071
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-03-26
##

random-match 'A-Za-z0-9\+' 40
