#!/bin/sh
set -euf

##
# Generate a Amazon Web Services (AWS) Access Key Id.
#
# The string is alphanumeric uppercase and 20 characters.
#
# Usage:
#
#     random-aws-access-key-id [n]
#
# Options:
#
#   * `n` is the number of characters; default is 20.
#
# Example:
#
#     $ random-aws-access-key-id
#     XQX20V9LO8ARDI10QFVG
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:upper:][:digit:]' "${1:-20}"
