#!/bin/sh
set -euf

##
# Generate a random email addr string.
#
# The string is lowercase.
#
# Usage:
#
#     random-email-addr [user n] [sld n] [tld n]
#
# Example:
#
#     $ random-email-addr
#     jpkhbvlc@srzuffit.xvh
#
# This implementation does:
#
#   * 8 character username
#
#   * 8 character second-level domain name
#
#   * 3 character top-level domain name
#
# Example format:
#
#     xxxxxxxx@xxxxxxxx.xxx
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

user=$(random-ascii '[:lower:]' "${1:-8}")
sld=$(random-ascii '[:lower]' "${1:-8}")
tld=$(random-ascii '[:lower:]' "${1:-3}")
printf "%s@%s.%s" "$user" "$sld" "$tld"
