#!/bin/sh
set -euf

##
# Generate a random string that looks like a SHA 256 checksum.
#
# Usage:
#
#     random-sha-256-checksum [n]
#
# Options:
#
#   * `n` is the number of characters; default is 44.
#
# Example:
#
#     $ random-sha-256
#     IBYMhAiRHPDJAamWSafFk+XirjkiTFqEGSFTOnWWTAVS
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:alnum:]\+' ${1-44}
