#!/bin/sh
set -euf

##
# Generate a random Facebook app API secret.
#
# This is a random MD5 hash.
#
# Usage:
#
#     random-facebook-app-api-secret
#
# Example:
#
#     $ random-facebook-app-api-secret
#     489bfc1cbe3f7705b306a944917fcc94
#
# See http://facebook.com
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-md5
