#!/bin/bash
set -euf -o pipefail

##
# Generate a random file that fills up forever with random data.
#
# This can be useful to wipe a disk drive, or for load testing, etc.
#
# The file name is a random 32-hex-character-lowercase string.
#
# Usage:
#
#     random-file-infinite
#
# Examples:
#
#     $ random-file-infinite
#     #=> write random data to file "76ba7ad7d9265466f2ad764c4d5859f5"
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-07-13
##

cat /dev/urandom > $(hexdump -n 16 -v -e '16/1 "%02x"' /dev/urandom)
