#!/bin/sh
set -euf

##
# Generate a random salt string.
#
# The string is suitable for using with Linux passwords,
# such as the `mkpasswd` command and `/etc/shadow` file.
#
#  * Characters are ASCII alphanumeric
#
#  * Default length 16.
#
# Usage:
#
#     random-salt [length]
#
# Example:
#
#     $ random-salt
#     zd05RAfxlh4Dg7F4
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-ascii '[:alnum:]' ${1-16}
