#!/bin/sh
set -euf

##
# Generate a random bcrypt salt string.
#
# The string is the prefix ''$2a$07$' then 22 alphanumeric characters.
#
# Usage:
#
#     random-bcrypt-salt [n]
#
# Options:
#
#   * `n` is the number of characters; default is 22.
#
# Example:
#
#     $ random-bcrypt-salt
#     $2a$07$PIcjwSQgSzExwIS4Qy9sOt
#
# Be aware that bcrypt uses this salt converted to base 64,
# which means that the final character may not be carrying
# information; in other words, two salts can differ in the
# final character yet still produce the same crypt text.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

x=$(random-ascii-alnum "${1-22}")
echo '$2a$07$'$x
