#!/bin/sh
set -euf

##
# Generate a random MD5 string.
#
# Usage:
#
#     random-md5
#
# Example:
#
#     $ random-md5
#     15e368b020138215126947ac5272aead
#
# This implementation uses `md5sum` or `md5`.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

md5=$(which md5sum md5 | grep -v "not found" | head -1)
dd if=/dev/urandom bs=1 count=32 2>/dev/null | $md5 | sed 's/ .*//'
