#!/bin/sh
set -euf

##
# Generate a random Trello board id
#
# This is a 24 character hexadecimal lowercase string.
#
# Usage:
#
#     random-trello-board-id
#
# Example:
#
#     $ random-trello-board-id
#     40ab84075d6a958ee6c5d5e8
#
# See https://www.trello.com/api
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T17:58:40Z
##

random-hex-lower 12
